server:
  port: 8081

spring:
  application:
    name: PEDIDOS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/pedidos_db
    password: pedidos_pass
    username: pedidos_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect